services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - rt_db

  backend:
    image: ghcr.io/russiatravel/backend:v1.0.1
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - .data:/app/.data:ro
    networks:
      - rt_db
      - rt_bot

  bot:
    image: ghcr.io/russiatravel/tgbot:v1.0.1
    env_file:
      - .env
    networks:
      - rt_bot

networks:
  rt_db:
  rt_bot:
